####JMS PROPERTIES
com:
    springframework:
        jmsusername: "jmssajol"
        jmspassword: "jmssajol"
        jmsurl: "jmssajol.com"

---
    spring:
        profiles: en
    com:
        springframework:
            jmsusername: jmssajol##en